---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splunk
  namespace: splunk
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: splunk-kkutova.com # ⛔ Replace with your domain
      http:
        paths:
          - path: /splunk
            pathType: Prefix
            backend:
              service:
                name: splunk
                port:
                  number: 8000
#tls:
#- hosts:
#- 3.75.96.190 # ⛔ Replace with your domain
#secretName: splunk-tls # Provide TLS secret if using HTTPS