apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4s-config
  namespace: sc4s
data:
  SC4S_DEST_SPLUNK_HEC_URL: "https://splunk-hec.splunk.svc.cluster.local:8088"
  SC4S_DEST_SPLUNK_HEC_TOKEN: "757b59dc-4787-4374-8b29-fa07740f44b9"
  SC4S_DEST_SPLUNK_HEC_TLS_VERIFY: "no"
  SC4S_LISTEN_DEFAULT_TCP_PORT: "514"
  SC4S_LISTEN_DEFAULT_UDP_PORT: "514"
  SC4S_USE_REVERSE_LOOKUP: "no"